server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/osahaneat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB

jwt:
  privateKey: 2Lg5npGxc/yIFoHA/E/iQnjAt3f1dqOcsmfeL0pANG4=

fileUpload:
  rootPath: E:\TuHoc\BaiTap_JavaSpringBoot\BE_WebPizza\upload